name: Nightly Package Update

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: false
        type: boolean
        description: Dry Run

# This is intentional change to prevent npm updates,
# otherwise it is causing an endless dependency update loop for fiftyone.* packages in this repository
#  schedule:
#    - cron: '0 1 * * *'

jobs:
  Nightly_Package_Update:
    uses: postindustria-tech/common-ci/.github/workflows/nightly-package-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
